import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import Button from "../components/common/Button";
import Card from "../components/common/Card";
import PageContainer from "../components/layout/PageContainer";
import SectionHeader from "../components/common/SectionHeader";
import api from "../services/api";

const PLAN_DETAILS = {
  basic: {
    label: "Basic Plan",
    coverage: [
      "UPI fraud incidents",
      "Account takeover protection",
      "Unauthorized transaction coverage",
    ],
  },
  advanced: {
    label: "Advanced Plan",
    coverage: [
      "Everything in Basic Plan",
      "Phishing and social engineering support",
      "High-risk fraud event protection",
    ],
  },
};

const ANNUAL_PREMIUM = {
  basic: 499,
  advanced: 999,
};

const formatInr = (value) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);

const getPremium = (planName, duration) => {
  const annual = ANNUAL_PREMIUM[planName] || 0;
  return Math.round((annual / 12) * duration);
};

const ConfirmPlan = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const planName = location.state?.planName;
  const duration = Number(location.state?.duration || 12);
  const endDate = location.state?.endDate;
  const isValidPlan = planName === "basic" || planName === "advanced";
  const hasValidState = Boolean(isValidPlan && endDate);

  const [agreed, setAgreed] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!hasValidState) {
      navigate("/plans", { replace: true });
    }
  }, [hasValidState, navigate]);

  const details = useMemo(() => PLAN_DETAILS[planName] || PLAN_DETAILS.basic, [planName]);
  const premium = useMemo(() => getPremium(planName, duration), [planName, duration]);

  if (!hasValidState) {
    return null;
  }

  const handleConfirm = async () => {
    if (loading || !agreed) return;

    try {
      setError("");
      setLoading(true);

      const response = await api.post("/policy/create", {
        planName,
        endDate,
      });

      if (response?.data?.success === false) {
        throw new Error(response?.data?.message || "Policy activation failed.");
      }

      navigate("/policies");
    } catch (err) {
      const message =
        err?.response?.data?.message ||
        err?.response?.data?.error ||
        err?.message ||
        "Could not activate policy. Please try again.";
      setError(message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageContainer>
      <SectionHeader
        title="Confirm Your Protection"
        subtitle="Review policy details, accept terms, and confirm activation."
      />

      <div style={styles.grid}>
        <Card variant="elevated" padding="lg" style={styles.summaryCard}>
          <h2 style={styles.cardTitle}>Policy Summary</h2>

          <div style={styles.row}>
            <span style={styles.label}>Plan</span>
            <span style={styles.value}>{details.label}</span>
          </div>
          <div style={styles.row}>
            <span style={styles.label}>Duration</span>
            <span style={styles.value}>{duration} months</span>
          </div>
          <div style={styles.row}>
            <span style={styles.label}>End Date</span>
            <span style={styles.value}>{endDate}</span>
          </div>
          <div style={styles.row}>
            <span style={styles.label}>Estimated Premium</span>
            <span style={styles.value}>{formatInr(premium)}</span>
          </div>

          <p style={styles.caption}>Final receipt details are generated by the backend at issuance.</p>

          <h3 style={styles.coverageTitle}>Coverage Includes</h3>
          <ul style={styles.coverageList}>
            {details.coverage.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </Card>

        <Card variant="subtle" padding="lg">
          <h2 style={styles.cardTitle}>Terms & Conditions</h2>
          <ul style={styles.termsList}>
            <li>Coverage applies only to listed protection modules.</li>
            <li>Claims require valid supporting documentation.</li>
            <li>Fraudulent claims may result in policy termination.</li>
            <li>DBS integrity can affect claim eligibility assessment.</li>
          </ul>

          <label style={styles.checkboxLabel}>
            <input
              type="checkbox"
              checked={agreed}
              onChange={(e) => setAgreed(e.target.checked)}
              disabled={loading}
            />
            <span>I agree to Sambhav Digital Protection Terms.</span>
          </label>

          {error ? <p style={styles.error}>{error}</p> : null}

          <div style={styles.actions}>
            <Button variant="ghost" onClick={() => navigate("/plans")} disabled={loading}>
              Back
            </Button>
            <Button onClick={handleConfirm} loading={loading} disabled={!agreed || loading}>
              Confirm Purchase
            </Button>
          </div>
        </Card>
      </div>
    </PageContainer>
  );
};

const styles = {
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "18px",
    alignItems: "start",
  },
  summaryCard: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  cardTitle: {
    margin: 0,
    fontSize: "20px",
    color: "var(--text-primary)",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
    borderBottom: "1px solid var(--border)",
    paddingBottom: "8px",
  },
  label: {
    color: "var(--text-secondary)",
    fontSize: "14px",
  },
  value: {
    color: "var(--text-primary)",
    fontWeight: 600,
    fontSize: "14px",
  },
  caption: {
    margin: "6px 0 0",
    fontSize: "12px",
    color: "var(--text-secondary)",
  },
  coverageTitle: {
    margin: "10px 0 0",
    color: "var(--text-primary)",
    fontSize: "16px",
  },
  coverageList: {
    margin: 0,
    paddingLeft: "18px",
    color: "var(--text-secondary)",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  termsList: {
    margin: "8px 0 0",
    paddingLeft: "18px",
    color: "var(--text-secondary)",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  checkboxLabel: {
    marginTop: "14px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "var(--text-primary)",
    fontSize: "14px",
  },
  error: {
    color: "#a12727",
    fontSize: "14px",
    marginTop: "10px",
    marginBottom: 0,
  },
  actions: {
    marginTop: "16px",
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
    flexWrap: "wrap",
  },
};

export default ConfirmPlan;
